//
// Copyright (C) 2000 Institut fuer Telematik, Universitaet Karlsruhe
// Copyright (C) 2004,2011 Andras Varga
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>.
//

cplusplus {{
#include "inet/common/Protocol.h"
#include "inet/common/IProtocolControlInfo.h"
#include "inet/common/ISocketControlInfo.h"
#include "inet/linklayer/common/Ieee802Ctrl.h"
#include "inet/networklayer/contract/INetworkProtocolControlInfo.h"
}}

namespace inet;

class IPSocketCommand
{
    @implements(ISocketControlInfo, IProtocolControlInfo);
    int controlInfoProtocolId = Protocol::ipv4.getId();
    int socketId;
}

class IPSocketBindCommand extends IPSocketCommand
{
    int protoclId;
}

class IPSocketCloseCommand extends IPSocketCommand
{
}
