#! /usr/bin/env python
# This script calls gitk with all historical folders of files of current folder.
#

import fnmatch
import os
import re
import string
import subprocess
import sys

rootPath = '.'
err = 0

paths = set()

for filename in os.listdir(rootPath):
    if True:
        fullpath = os.path.join(rootPath, filename)
        proc = subprocess.Popen(['git', 'log', '-p', '--follow', fullpath], stdout=subprocess.PIPE)
        for line in proc.stdout:
            if line.startswith('diff --git '):
                line = line[11:].rstrip()
                for onefile in line.split(' '):
                    onefile = onefile[2:]
                    histdir = os.path.dirname(onefile)
                    paths.add(histdir)
#                    print dirname+': '+histdir

gitdir = subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).rstrip()
os.chdir(gitdir)

cmd = ['gitk', '--'] + sorted(paths)
print ' '.join(cmd)
subprocess.call(cmd)
