#!/usr/bin/env python

import argparse
import copy
import csv
import glob
import multiprocessing
import os
import re
import subprocess
import sys
import threading
import time
import unittest
from StringIO import StringIO


inetRoot = os.path.abspath("../..")
workingdir = inetRoot + "/examples/mobility"
sep = ";" if sys.platform == 'win32' else ':'
nedPath = inetRoot + "/src" + sep + inetRoot + "/examples"
inetLib = inetRoot + "/src/inet"
opp_run = "opp_run"
cpuTimeLimit = "2s"
logFile = "test.out"
testConfigs = "testConfigs.txt"
iniFile = "test.ini"

if __name__ == "__main__":
    file = open(testConfigs, "r")
    for line in file:
        config = line.rstrip()
        command = opp_run + " " + iniFile + " -c " + config + \
            " -n " + nedPath + " -l " + inetLib + " -u Cmdenv " + \
            " --cpu-time-limit=" + cpuTimeLimit + \
            " --vector-recording=false --scalar-recording=false"
        process = subprocess.Popen(command, shell=True, cwd=workingdir, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        out = process.communicate()[0]  

